// AUTO-GENERATED from eachlabs LLM Router model enum.
// Source: https://crm.eachlabs.ai/v1/model?slug=eachlabs-llm-router
// Do not edit by hand — regenerate by running scripts/sync-llm-router.ts.

export type LlmRouterModel = {
  /** Identifier accepted by the eachlabs-llm-router `model` input. */
  routerSlug: string;
  /** URL-safe slug used in /explore/llms/[slug] routes. */
  urlSlug: string;
  /** Human-readable model name. */
  name: string;
  /** Top-level provider key (e.g. "anthropic"). */
  providerSlug: string;
  /** Display label for the provider. */
  providerName: string;
  /** Family path inside the provider, if the router slug has 3+ segments. */
  familySlug: string | null;
  /** Raw model identifier after the provider prefix. */
  modelName: string;
};

export const llmRouterModels: ReadonlyArray<LlmRouterModel> = [
  {
    routerSlug: "anthropic/claude-sonnet-4",
    urlSlug: "anthropic--claude-sonnet-4",
    name: "Claude Sonnet 4",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-sonnet-4",
  },
  {
    routerSlug: "anthropic/claude-opus-4-6",
    urlSlug: "anthropic--claude-opus-4-6",
    name: "Claude Opus 4 6",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-opus-4-6",
  },
  {
    routerSlug: "anthropic/claude-3-5-haiku",
    urlSlug: "anthropic--claude-3-5-haiku",
    name: "Claude 3 5 Haiku",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-3-5-haiku",
  },
  {
    routerSlug: "anthropic/claude-opus-4",
    urlSlug: "anthropic--claude-opus-4",
    name: "Claude Opus 4",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-opus-4",
  },
  {
    routerSlug: "anthropic/claude-sonnet-4-5",
    urlSlug: "anthropic--claude-sonnet-4-5",
    name: "Claude Sonnet 4 5",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-sonnet-4-5",
  },
  {
    routerSlug: "anthropic/claude-sonnet-4-6",
    urlSlug: "anthropic--claude-sonnet-4-6",
    name: "Claude Sonnet 4 6",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-sonnet-4-6",
  },
  {
    routerSlug: "anthropic/claude-3-haiku",
    urlSlug: "anthropic--claude-3-haiku",
    name: "Claude 3 Haiku",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-3-haiku",
  },
  {
    routerSlug: "anthropic/claude-haiku-4-5",
    urlSlug: "anthropic--claude-haiku-4-5",
    name: "Claude Haiku 4 5",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-haiku-4-5",
  },
  {
    routerSlug: "anthropic/claude-opus-4-5",
    urlSlug: "anthropic--claude-opus-4-5",
    name: "Claude Opus 4 5",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-opus-4-5",
  },
  {
    routerSlug: "anthropic/claude-3-7-sonnet",
    urlSlug: "anthropic--claude-3-7-sonnet",
    name: "Claude 3 7 Sonnet",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-3-7-sonnet",
  },
  {
    routerSlug: "anthropic/claude-opus-4-1",
    urlSlug: "anthropic--claude-opus-4-1",
    name: "Claude Opus 4 1",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    familySlug: null,
    modelName: "claude-opus-4-1",
  },
  {
    routerSlug: "openai-responses/gpt-4.1-mini",
    urlSlug: "openai-responses--gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-4.1-mini",
  },
  {
    routerSlug: "openai-responses/gpt-5.1-codex",
    urlSlug: "openai-responses--gpt-5.1-codex",
    name: "GPT 5.1 Codex",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5.1-codex",
  },
  {
    routerSlug: "openai-responses/gpt-5-mini",
    urlSlug: "openai-responses--gpt-5-mini",
    name: "GPT 5 Mini",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5-mini",
  },
  {
    routerSlug: "openai-responses/gpt-5",
    urlSlug: "openai-responses--gpt-5",
    name: "GPT 5",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5",
  },
  {
    routerSlug: "openai-responses/o3-pro",
    urlSlug: "openai-responses--o3-pro",
    name: "O3 Pro",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "o3-pro",
  },
  {
    routerSlug: "openai-responses/gpt-5.2-codex",
    urlSlug: "openai-responses--gpt-5.2-codex",
    name: "GPT 5.2 Codex",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5.2-codex",
  },
  {
    routerSlug: "openai-responses/gpt-5-pro",
    urlSlug: "openai-responses--gpt-5-pro",
    name: "GPT 5 Pro",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5-pro",
  },
  {
    routerSlug: "openai-responses/gpt-5.2",
    urlSlug: "openai-responses--gpt-5.2",
    name: "GPT 5.2",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5.2",
  },
  {
    routerSlug: "openai-responses/gpt-5-codex",
    urlSlug: "openai-responses--gpt-5-codex",
    name: "GPT 5 Codex",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5-codex",
  },
  {
    routerSlug: "openai-responses/o3-mini",
    urlSlug: "openai-responses--o3-mini",
    name: "O3 Mini",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "o3-mini",
  },
  {
    routerSlug: "openai-responses/o4-mini",
    urlSlug: "openai-responses--o4-mini",
    name: "O4 Mini",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "o4-mini",
  },
  {
    routerSlug: "openai-responses/gpt-4.1",
    urlSlug: "openai-responses--gpt-4.1",
    name: "GPT 4.1",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-4.1",
  },
  {
    routerSlug: "openai-responses/gpt-4.1-nano",
    urlSlug: "openai-responses--gpt-4.1-nano",
    name: "GPT 4.1 Nano",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-4.1-nano",
  },
  {
    routerSlug: "openai-responses/gpt-5-nano",
    urlSlug: "openai-responses--gpt-5-nano",
    name: "GPT 5 Nano",
    providerSlug: "openai-responses",
    providerName: "OpenAI (Responses)",
    familySlug: null,
    modelName: "gpt-5-nano",
  },
  {
    routerSlug: "nebius/moonshotai/Kimi-K2-Instruct",
    urlSlug: "nebius--moonshotai--Kimi-K2-Instruct",
    name: "Kimi K2 Instruct",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "moonshotai",
    modelName: "Kimi-K2-Instruct",
  },
  {
    routerSlug: "nebius/Qwen/Qwen3-Coder-480B-A35B-Instruct",
    urlSlug: "nebius--Qwen--Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "Qwen",
    modelName: "Qwen3-Coder-480B-A35B-Instruct",
  },
  {
    routerSlug: "nebius/zai-org/GLM-4.5",
    urlSlug: "nebius--zai-org--GLM-4.5",
    name: "GLM 4.5",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "zai-org",
    modelName: "GLM-4.5",
  },
  {
    routerSlug: "nebius/deepseek-ai/DeepSeek-V3-0324",
    urlSlug: "nebius--deepseek-ai--DeepSeek-V3-0324",
    name: "DeepSeek V3 0324",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-V3-0324",
  },
  {
    routerSlug: "nebius/deepseek-ai/DeepSeek-R1-0528",
    urlSlug: "nebius--deepseek-ai--DeepSeek-R1-0528",
    name: "DeepSeek R1 0528",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-R1-0528",
  },
  {
    routerSlug: "nebius/meta-llama/Llama-3.3-70B-Instruct",
    urlSlug: "nebius--meta-llama--Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "meta-llama",
    modelName: "Llama-3.3-70B-Instruct",
  },
  {
    routerSlug: "nebius/deepseek-ai/DeepSeek-V3-0324-fast",
    urlSlug: "nebius--deepseek-ai--DeepSeek-V3-0324-fast",
    name: "DeepSeek V3 0324 Fast",
    providerSlug: "nebius",
    providerName: "Nebius",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-V3-0324-fast",
  },
  {
    routerSlug: "azure/openai-responses/gpt-4.1",
    urlSlug: "azure--openai-responses--gpt-4.1",
    name: "GPT 4.1",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: "openai-responses",
    modelName: "gpt-4.1",
  },
  {
    routerSlug: "azure/gpt-4.1-mini",
    urlSlug: "azure--gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-4.1-mini",
  },
  {
    routerSlug: "azure/gpt-5-mini",
    urlSlug: "azure--gpt-5-mini",
    name: "GPT 5 Mini",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-5-mini",
  },
  {
    routerSlug: "azure/openai-responses/gpt-4.1-nano",
    urlSlug: "azure--openai-responses--gpt-4.1-nano",
    name: "GPT 4.1 Nano",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: "openai-responses",
    modelName: "gpt-4.1-nano",
  },
  {
    routerSlug: "azure/gpt-5.2",
    urlSlug: "azure--gpt-5.2",
    name: "GPT 5.2",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-5.2",
  },
  {
    routerSlug: "azure/gpt-5-nano",
    urlSlug: "azure--gpt-5-nano",
    name: "GPT 5 Nano",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-5-nano",
  },
  {
    routerSlug: "azure/o4-mini",
    urlSlug: "azure--o4-mini",
    name: "O4 Mini",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "o4-mini",
  },
  {
    routerSlug: "azure/gpt-4.1-nano",
    urlSlug: "azure--gpt-4.1-nano",
    name: "GPT 4.1 Nano",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-4.1-nano",
  },
  {
    routerSlug: "azure/openai-responses/gpt-5.2-codex",
    urlSlug: "azure--openai-responses--gpt-5.2-codex",
    name: "GPT 5.2 Codex",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: "openai-responses",
    modelName: "gpt-5.2-codex",
  },
  {
    routerSlug: "azure/gpt-4.1",
    urlSlug: "azure--gpt-4.1",
    name: "GPT 4.1",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-4.1",
  },
  {
    routerSlug: "azure/gpt-5",
    urlSlug: "azure--gpt-5",
    name: "GPT 5",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-5",
  },
  {
    routerSlug: "azure/openai-responses/gpt-4.1-mini",
    urlSlug: "azure--openai-responses--gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: "openai-responses",
    modelName: "gpt-4.1-mini",
  },
  {
    routerSlug: "azure/openai-responses/gpt-5.2-codex",
    urlSlug: "azure--openai-responses--gpt-5.2-codex",
    name: "GPT 5.2 Codex",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: "openai-responses",
    modelName: "gpt-5.2-codex",
  },
  {
    routerSlug: "azure/gpt-5.1",
    urlSlug: "azure--gpt-5.1",
    name: "GPT 5.1",
    providerSlug: "azure",
    providerName: "Azure OpenAI",
    familySlug: null,
    modelName: "gpt-5.1",
  },
  {
    routerSlug: "bedrock/claude-opus-4-5",
    urlSlug: "bedrock--claude-opus-4-5",
    name: "Claude Opus 4 5",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-opus-4-5",
  },
  {
    routerSlug: "bedrock/claude-sonnet-4",
    urlSlug: "bedrock--claude-sonnet-4",
    name: "Claude Sonnet 4",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-sonnet-4",
  },
  {
    routerSlug: "bedrock/claude-opus-4",
    urlSlug: "bedrock--claude-opus-4",
    name: "Claude Opus 4",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-opus-4",
  },
  {
    routerSlug: "bedrock/claude-haiku-4-5",
    urlSlug: "bedrock--claude-haiku-4-5",
    name: "Claude Haiku 4 5",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-haiku-4-5",
  },
  {
    routerSlug: "bedrock/claude-3-7-sonnet",
    urlSlug: "bedrock--claude-3-7-sonnet",
    name: "Claude 3 7 Sonnet",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-3-7-sonnet",
  },
  {
    routerSlug: "bedrock/claude-opus-4-6",
    urlSlug: "bedrock--claude-opus-4-6",
    name: "Claude Opus 4 6",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-opus-4-6",
  },
  {
    routerSlug: "bedrock/claude-sonnet-4-5",
    urlSlug: "bedrock--claude-sonnet-4-5",
    name: "Claude Sonnet 4 5",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-sonnet-4-5",
  },
  {
    routerSlug: "bedrock/claude-sonnet-4",
    urlSlug: "bedrock--claude-sonnet-4",
    name: "Claude Sonnet 4",
    providerSlug: "bedrock",
    providerName: "AWS Bedrock",
    familySlug: null,
    modelName: "claude-sonnet-4",
  },
  {
    routerSlug: "together/meta-llama/Llama-3.2-3B-Instruct-Turbo",
    urlSlug: "together--meta-llama--Llama-3.2-3B-Instruct-Turbo",
    name: "Llama 3.2 3B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "Llama-3.2-3B-Instruct-Turbo",
  },
  {
    routerSlug: "together/meta-llama/Llama-3.3-70B-Instruct-Turbo",
    urlSlug: "together--meta-llama--Llama-3.3-70B-Instruct-Turbo",
    name: "Llama 3.3 70B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "Llama-3.3-70B-Instruct-Turbo",
  },
  {
    routerSlug: "together/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
    urlSlug: "together--meta-llama--Meta-Llama-3.1-70B-Instruct-Turbo",
    name: "Meta Llama 3.1 70B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3.1-70B-Instruct-Turbo",
  },
  {
    routerSlug: "together/deepseek-ai/DeepSeek-V3",
    urlSlug: "together--deepseek-ai--DeepSeek-V3",
    name: "DeepSeek V3",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-V3",
  },
  {
    routerSlug: "together/Qwen/Qwen2.5-7B-Instruct-Turbo",
    urlSlug: "together--Qwen--Qwen2.5-7B-Instruct-Turbo",
    name: "Qwen2.5 7B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "Qwen",
    modelName: "Qwen2.5-7B-Instruct-Turbo",
  },
  {
    routerSlug: "together/deepseek-ai/DeepSeek-R1",
    urlSlug: "together--deepseek-ai--DeepSeek-R1",
    name: "DeepSeek R1",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-R1",
  },
  {
    routerSlug: "together/Qwen/Qwen2.5-72B-Instruct-Turbo",
    urlSlug: "together--Qwen--Qwen2.5-72B-Instruct-Turbo",
    name: "Qwen2.5 72B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "Qwen",
    modelName: "Qwen2.5-72B-Instruct-Turbo",
  },
  {
    routerSlug: "together/meta-llama/LlamaGuard-2-8b",
    urlSlug: "together--meta-llama--LlamaGuard-2-8b",
    name: "LlamaGuard 2 8b",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "LlamaGuard-2-8b",
  },
  {
    routerSlug: "together/meta-llama/Meta-Llama-3-8B-Instruct-Lite",
    urlSlug: "together--meta-llama--Meta-Llama-3-8B-Instruct-Lite",
    name: "Meta Llama 3 8B Instruct Lite",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3-8B-Instruct-Lite",
  },
  {
    routerSlug: "together/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    urlSlug: "together--meta-llama--Meta-Llama-3.1-8B-Instruct-Turbo",
    name: "Meta Llama 3.1 8B Instruct Turbo",
    providerSlug: "together",
    providerName: "Together AI",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3.1-8B-Instruct-Turbo",
  },
  {
    routerSlug: "novita/deepseek/deepseek-r1-distill-qwen-32b",
    urlSlug: "novita--deepseek--deepseek-r1-distill-qwen-32b",
    name: "Deepseek R1 Distill Qwen 32b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-r1-distill-qwen-32b",
  },
  {
    routerSlug: "novita/deepseek/deepseek-prover-v2-671b",
    urlSlug: "novita--deepseek--deepseek-prover-v2-671b",
    name: "Deepseek Prover V2 671b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-prover-v2-671b",
  },
  {
    routerSlug: "novita/meta-llama/llama-3.2-3b-instruct",
    urlSlug: "novita--meta-llama--llama-3.2-3b-instruct",
    name: "Llama 3.2 3b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3.2-3b-instruct",
  },
  {
    routerSlug: "novita/deepseek/deepseek-r1-distill-llama-70b",
    urlSlug: "novita--deepseek--deepseek-r1-distill-llama-70b",
    name: "Deepseek R1 Distill Llama 70b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-r1-distill-llama-70b",
  },
  {
    routerSlug: "novita/sao10k/l3-8b-lunaris",
    urlSlug: "novita--sao10k--l3-8b-lunaris",
    name: "L3 8b Lunaris",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "sao10k",
    modelName: "l3-8b-lunaris",
  },
  {
    routerSlug: "novita/meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
    urlSlug: "novita--meta-llama--llama-4-maverick-17b-128e-instruct-fp8",
    name: "Llama 4 Maverick 17b 128e Instruct FP8",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-4-maverick-17b-128e-instruct-fp8",
  },
  {
    routerSlug: "novita/zai-org/glm-4.5",
    urlSlug: "novita--zai-org--glm-4.5",
    name: "GLM 4.5",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "zai-org",
    modelName: "glm-4.5",
  },
  {
    routerSlug: "novita/meta-llama/llama-3-8b-instruct",
    urlSlug: "novita--meta-llama--llama-3-8b-instruct",
    name: "Llama 3 8b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3-8b-instruct",
  },
  {
    routerSlug: "novita/deepseek/deepseek-r1-turbo",
    urlSlug: "novita--deepseek--deepseek-r1-turbo",
    name: "Deepseek R1 Turbo",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-r1-turbo",
  },
  {
    routerSlug: "novita/zai-org/glm-4.6",
    urlSlug: "novita--zai-org--glm-4.6",
    name: "GLM 4.6",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "zai-org",
    modelName: "glm-4.6",
  },
  {
    routerSlug: "novita/sao10k/l3-70b-euryale-v2.1",
    urlSlug: "novita--sao10k--l3-70b-euryale-v2.1",
    name: "L3 70b Euryale V2.1",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "sao10k",
    modelName: "l3-70b-euryale-v2.1",
  },
  {
    routerSlug: "novita/sao10k/l31-70b-euryale-v2.2",
    urlSlug: "novita--sao10k--l31-70b-euryale-v2.2",
    name: "L31 70b Euryale V2.2",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "sao10k",
    modelName: "l31-70b-euryale-v2.2",
  },
  {
    routerSlug: "novita/meta-llama/llama-3-70b-instruct",
    urlSlug: "novita--meta-llama--llama-3-70b-instruct",
    name: "Llama 3 70b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3-70b-instruct",
  },
  {
    routerSlug: "novita/nousresearch/hermes-2-pro-llama-3-8b",
    urlSlug: "novita--nousresearch--hermes-2-pro-llama-3-8b",
    name: "Hermes 2 Pro Llama 3 8b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "nousresearch",
    modelName: "hermes-2-pro-llama-3-8b",
  },
  {
    routerSlug: "novita/deepseek/deepseek-r1-distill-qwen-14b",
    urlSlug: "novita--deepseek--deepseek-r1-distill-qwen-14b",
    name: "Deepseek R1 Distill Qwen 14b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-r1-distill-qwen-14b",
  },
  {
    routerSlug: "novita/deepseek/deepseek-r1",
    urlSlug: "novita--deepseek--deepseek-r1",
    name: "Deepseek R1",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-r1",
  },
  {
    routerSlug: "novita/qwen/qwen3-235b-a22b-fp8",
    urlSlug: "novita--qwen--qwen3-235b-a22b-fp8",
    name: "Qwen3 235b A22b FP8",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "qwen",
    modelName: "qwen3-235b-a22b-fp8",
  },
  {
    routerSlug: "novita/microsoft/wizardlm-2-8x22b",
    urlSlug: "novita--microsoft--wizardlm-2-8x22b",
    name: "Wizardlm 2 8x22b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "microsoft",
    modelName: "wizardlm-2-8x22b",
  },
  {
    routerSlug: "novita/deepseek/deepseek-v3-turbo",
    urlSlug: "novita--deepseek--deepseek-v3-turbo",
    name: "Deepseek V3 Turbo",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-v3-turbo",
  },
  {
    routerSlug: "novita/meta-llama/llama-3.3-70b-instruct",
    urlSlug: "novita--meta-llama--llama-3.3-70b-instruct",
    name: "Llama 3.3 70b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3.3-70b-instruct",
  },
  {
    routerSlug: "novita/deepseek/deepseek_v3",
    urlSlug: "novita--deepseek--deepseek_v3",
    name: "Deepseek V3",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek_v3",
  },
  {
    routerSlug: "novita/moonshotai/kimi-k2-instruct",
    urlSlug: "novita--moonshotai--kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "moonshotai",
    modelName: "kimi-k2-instruct",
  },
  {
    routerSlug: "novita/gryphe/mythomax-l2-13b",
    urlSlug: "novita--gryphe--mythomax-l2-13b",
    name: "Mythomax L2 13b",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "gryphe",
    modelName: "mythomax-l2-13b",
  },
  {
    routerSlug: "novita/deepseek/deepseek-v3-0324",
    urlSlug: "novita--deepseek--deepseek-v3-0324",
    name: "Deepseek V3 0324",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "deepseek",
    modelName: "deepseek-v3-0324",
  },
  {
    routerSlug: "novita/qwen/qwen-2.5-72b-instruct",
    urlSlug: "novita--qwen--qwen-2.5-72b-instruct",
    name: "Qwen 2.5 72b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "qwen",
    modelName: "qwen-2.5-72b-instruct",
  },
  {
    routerSlug: "novita/mistralai/mistral-nemo",
    urlSlug: "novita--mistralai--mistral-nemo",
    name: "Mistral Nemo",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "mistralai",
    modelName: "mistral-nemo",
  },
  {
    routerSlug: "novita/meta-llama/llama-3.2-1b-instruct",
    urlSlug: "novita--meta-llama--llama-3.2-1b-instruct",
    name: "Llama 3.2 1b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3.2-1b-instruct",
  },
  {
    routerSlug: "novita/Sao10K/L3-8B-Stheno-v3.2",
    urlSlug: "novita--Sao10K--L3-8B-Stheno-v3.2",
    name: "L3 8B Stheno V3.2",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "Sao10K",
    modelName: "L3-8B-Stheno-v3.2",
  },
  {
    routerSlug: "novita/qwen/qwen2.5-vl-72b-instruct",
    urlSlug: "novita--qwen--qwen2.5-vl-72b-instruct",
    name: "Qwen2.5 VL 72b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "qwen",
    modelName: "qwen2.5-vl-72b-instruct",
  },
  {
    routerSlug: "novita/meta-llama/llama-3.1-8b-instruct",
    urlSlug: "novita--meta-llama--llama-3.1-8b-instruct",
    name: "Llama 3.1 8b Instruct",
    providerSlug: "novita",
    providerName: "Novita",
    familySlug: "meta-llama",
    modelName: "llama-3.1-8b-instruct",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219",
    urlSlug: "coding--claude-3-7-sonnet-20250219",
    name: "Claude 3 7 Sonnet 20250219",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219",
  },
  {
    routerSlug: "coding/claude-sonnet-4-20250514",
    urlSlug: "coding--claude-sonnet-4-20250514",
    name: "Claude Sonnet 4 20250514",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-sonnet-4-20250514",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:8192",
    urlSlug: "coding--claude-3-7-sonnet-20250219__8192",
    name: "Claude 3 7 Sonnet 20250219:8192",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:8192",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:max",
    urlSlug: "coding--claude-3-7-sonnet-20250219__max",
    name: "Claude 3 7 Sonnet 20250219:max",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:max",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:16384",
    urlSlug: "coding--claude-3-7-sonnet-20250219__16384",
    name: "Claude 3 7 Sonnet 20250219:16384",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:16384",
  },
  {
    routerSlug: "coding/gemini-2.5-pro",
    urlSlug: "coding--gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "gemini-2.5-pro",
  },
  {
    routerSlug: "coding/gemini-2.5-flash",
    urlSlug: "coding--gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "gemini-2.5-flash",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:1024",
    urlSlug: "coding--claude-3-7-sonnet-20250219__1024",
    name: "Claude 3 7 Sonnet 20250219:1024",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:1024",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:medium",
    urlSlug: "coding--claude-3-7-sonnet-20250219__medium",
    name: "Claude 3 7 Sonnet 20250219:medium",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:medium",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:high",
    urlSlug: "coding--claude-3-7-sonnet-20250219__high",
    name: "Claude 3 7 Sonnet 20250219:high",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:high",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:64000",
    urlSlug: "coding--claude-3-7-sonnet-20250219__64000",
    name: "Claude 3 7 Sonnet 20250219:64000",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:64000",
  },
  {
    routerSlug: "coding/claude-3-7-sonnet-20250219:low",
    urlSlug: "coding--claude-3-7-sonnet-20250219__low",
    name: "Claude 3 7 Sonnet 20250219:low",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-3-7-sonnet-20250219:low",
  },
  {
    routerSlug: "coding/claude-opus-4-20250514",
    urlSlug: "coding--claude-opus-4-20250514",
    name: "Claude Opus 4 20250514",
    providerSlug: "coding",
    providerName: "eachlabs Coding",
    familySlug: null,
    modelName: "claude-opus-4-20250514",
  },
  {
    routerSlug: "deepseek/deepseek-chat",
    urlSlug: "deepseek--deepseek-chat",
    name: "Deepseek Chat",
    providerSlug: "deepseek",
    providerName: "DeepSeek",
    familySlug: null,
    modelName: "deepseek-chat",
  },
  {
    routerSlug: "deepseek/deepseek-reasoner",
    urlSlug: "deepseek--deepseek-reasoner",
    name: "Deepseek Reasoner",
    providerSlug: "deepseek",
    providerName: "DeepSeek",
    familySlug: null,
    modelName: "deepseek-reasoner",
  },
  {
    routerSlug: "parasail/parasail-kimi-k2-instruct",
    urlSlug: "parasail--parasail-kimi-k2-instruct",
    name: "Parasail Kimi K2 Instruct",
    providerSlug: "parasail",
    providerName: "Parasail",
    familySlug: null,
    modelName: "parasail-kimi-k2-instruct",
  },
  {
    routerSlug: "parasail/parasail-qwen25-vl-72b-instruct",
    urlSlug: "parasail--parasail-qwen25-vl-72b-instruct",
    name: "Parasail Qwen25 VL 72b Instruct",
    providerSlug: "parasail",
    providerName: "Parasail",
    familySlug: null,
    modelName: "parasail-qwen25-vl-72b-instruct",
  },
  {
    routerSlug: "parasail/parasail-gemma3-27b-it",
    urlSlug: "parasail--parasail-gemma3-27b-it",
    name: "Parasail Gemma3 27b It",
    providerSlug: "parasail",
    providerName: "Parasail",
    familySlug: null,
    modelName: "parasail-gemma3-27b-it",
  },
  {
    routerSlug: "parasail/parasail-qwen3-235b-a22b-instruct-2507",
    urlSlug: "parasail--parasail-qwen3-235b-a22b-instruct-2507",
    name: "Parasail Qwen3 235b A22b Instruct 2507",
    providerSlug: "parasail",
    providerName: "Parasail",
    familySlug: null,
    modelName: "parasail-qwen3-235b-a22b-instruct-2507",
  },
  {
    routerSlug: "zai/GLM-4.6",
    urlSlug: "zai--GLM-4.6",
    name: "GLM 4.6",
    providerSlug: "zai",
    providerName: "Z.AI",
    familySlug: null,
    modelName: "GLM-4.6",
  },
  {
    routerSlug: "zai/GLM-5",
    urlSlug: "zai--GLM-5",
    name: "GLM 5",
    providerSlug: "zai",
    providerName: "Z.AI",
    familySlug: null,
    modelName: "GLM-5",
  },
  {
    routerSlug: "zai/GLM-4.7",
    urlSlug: "zai--GLM-4.7",
    name: "GLM 4.7",
    providerSlug: "zai",
    providerName: "Z.AI",
    familySlug: null,
    modelName: "GLM-4.7",
  },
  {
    routerSlug: "zai/GLM-4.5",
    urlSlug: "zai--GLM-4.5",
    name: "GLM 4.5",
    providerSlug: "zai",
    providerName: "Z.AI",
    familySlug: null,
    modelName: "GLM-4.5",
  },
  {
    routerSlug: "xai/grok-2-1212",
    urlSlug: "xai--grok-2-1212",
    name: "Grok 2 1212",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-2-1212",
  },
  {
    routerSlug: "xai/grok-4-fast-non-reasoning",
    urlSlug: "xai--grok-4-fast-non-reasoning",
    name: "Grok 4 Fast Non Reasoning",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-4-fast-non-reasoning",
  },
  {
    routerSlug: "xai/grok-4",
    urlSlug: "xai--grok-4",
    name: "Grok 4",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-4",
  },
  {
    routerSlug: "xai/grok-4-fast",
    urlSlug: "xai--grok-4-fast",
    name: "Grok 4 Fast",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-4-fast",
  },
  {
    routerSlug: "xai/grok-code-fast-1",
    urlSlug: "xai--grok-code-fast-1",
    name: "Grok Code Fast 1",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-code-fast-1",
  },
  {
    routerSlug: "xai/grok-3-mini",
    urlSlug: "xai--grok-3-mini",
    name: "Grok 3 Mini",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-3-mini",
  },
  {
    routerSlug: "xai/grok-3-mini:low",
    urlSlug: "xai--grok-3-mini__low",
    name: "Grok 3 Mini:low",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-3-mini:low",
  },
  {
    routerSlug: "xai/grok-3-mini:high",
    urlSlug: "xai--grok-3-mini__high",
    name: "Grok 3 Mini:high",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-3-mini:high",
  },
  {
    routerSlug: "xai/grok-3",
    urlSlug: "xai--grok-3",
    name: "Grok 3",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-3",
  },
  {
    routerSlug: "xai/grok-4-1-fast-reasoning",
    urlSlug: "xai--grok-4-1-fast-reasoning",
    name: "Grok 4 1 Fast Reasoning",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-4-1-fast-reasoning",
  },
  {
    routerSlug: "xai/grok-4-1-fast-non-reasoning",
    urlSlug: "xai--grok-4-1-fast-non-reasoning",
    name: "Grok 4 1 Fast Non Reasoning",
    providerSlug: "xai",
    providerName: "xAI",
    familySlug: null,
    modelName: "grok-4-1-fast-non-reasoning",
  },
  {
    routerSlug: "mistral/pixtral-large-latest",
    urlSlug: "mistral--pixtral-large-latest",
    name: "Pixtral Large Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "pixtral-large-latest",
  },
  {
    routerSlug: "mistral/devstral-small-latest",
    urlSlug: "mistral--devstral-small-latest",
    name: "Devstral Small Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "devstral-small-latest",
  },
  {
    routerSlug: "mistral/codestral-latest",
    urlSlug: "mistral--codestral-latest",
    name: "Codestral Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "codestral-latest",
  },
  {
    routerSlug: "mistral/mistral-small-latest",
    urlSlug: "mistral--mistral-small-latest",
    name: "Mistral Small Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "mistral-small-latest",
  },
  {
    routerSlug: "mistral/open-mistral-7b",
    urlSlug: "mistral--open-mistral-7b",
    name: "Open Mistral 7b",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "open-mistral-7b",
  },
  {
    routerSlug: "mistral/mistral-large-latest",
    urlSlug: "mistral--mistral-large-latest",
    name: "Mistral Large Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "mistral-large-latest",
  },
  {
    routerSlug: "mistral/devstral-small-2507",
    urlSlug: "mistral--devstral-small-2507",
    name: "Devstral Small 2507",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "devstral-small-2507",
  },
  {
    routerSlug: "mistral/mistral-medium-latest",
    urlSlug: "mistral--mistral-medium-latest",
    name: "Mistral Medium Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "mistral-medium-latest",
  },
  {
    routerSlug: "mistral/devstral-medium-2507",
    urlSlug: "mistral--devstral-medium-2507",
    name: "Devstral Medium 2507",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "devstral-medium-2507",
  },
  {
    routerSlug: "mistral/devstral-latest",
    urlSlug: "mistral--devstral-latest",
    name: "Devstral Latest",
    providerSlug: "mistral",
    providerName: "Mistral",
    familySlug: null,
    modelName: "devstral-latest",
  },
  {
    routerSlug: "openai/gpt-4o-2024-08-06",
    urlSlug: "openai--gpt-4o-2024-08-06",
    name: "GPT 4o 2024 08 06",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4o-2024-08-06",
  },
  {
    routerSlug: "openai/gpt-4o-mini",
    urlSlug: "openai--gpt-4o-mini",
    name: "GPT 4o Mini",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4o-mini",
  },
  {
    routerSlug: "openai/gpt-4o-2024-11-20",
    urlSlug: "openai--gpt-4o-2024-11-20",
    name: "GPT 4o 2024 11 20",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4o-2024-11-20",
  },
  {
    routerSlug: "openai/o4-mini:high",
    urlSlug: "openai--o4-mini__high",
    name: "O4 Mini:high",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini:high",
  },
  {
    routerSlug: "openai/o1:medium",
    urlSlug: "openai--o1__medium",
    name: "O1:medium",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o1:medium",
  },
  {
    routerSlug: "openai/o3-mini:low",
    urlSlug: "openai--o3-mini__low",
    name: "O3 Mini:low",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3-mini:low",
  },
  {
    routerSlug: "openai/gpt-5:flex",
    urlSlug: "openai--gpt-5__flex",
    name: "GPT 5:flex",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5:flex",
  },
  {
    routerSlug: "openai/o3-deep-research",
    urlSlug: "openai--o3-deep-research",
    name: "O3 Deep Research",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3-deep-research",
  },
  {
    routerSlug: "openai/gpt-4.1-mini",
    urlSlug: "openai--gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4.1-mini",
  },
  {
    routerSlug: "openai/o3:flex",
    urlSlug: "openai--o3__flex",
    name: "O3:flex",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3:flex",
  },
  {
    routerSlug: "openai/o4-mini:low",
    urlSlug: "openai--o4-mini__low",
    name: "O4 Mini:low",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini:low",
  },
  {
    routerSlug: "openai/o4-mini:flex",
    urlSlug: "openai--o4-mini__flex",
    name: "O4 Mini:flex",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini:flex",
  },
  {
    routerSlug: "openai/chatgpt-4o",
    urlSlug: "openai--chatgpt-4o",
    name: "Chatgpt 4o",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "chatgpt-4o",
  },
  {
    routerSlug: "openai/gpt-5:priority",
    urlSlug: "openai--gpt-5__priority",
    name: "GPT 5:priority",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5:priority",
  },
  {
    routerSlug: "openai/gpt-4.1",
    urlSlug: "openai--gpt-4.1",
    name: "GPT 4.1",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4.1",
  },
  {
    routerSlug: "openai/o3-mini",
    urlSlug: "openai--o3-mini",
    name: "O3 Mini",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3-mini",
  },
  {
    routerSlug: "openai/gpt-5-mini:flex",
    urlSlug: "openai--gpt-5-mini__flex",
    name: "GPT 5 Mini:flex",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-mini:flex",
  },
  {
    routerSlug: "openai/o3",
    urlSlug: "openai--o3",
    name: "O3",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3",
  },
  {
    routerSlug: "openai/o4-mini",
    urlSlug: "openai--o4-mini",
    name: "O4 Mini",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini",
  },
  {
    routerSlug: "openai/o1:high",
    urlSlug: "openai--o1__high",
    name: "O1:high",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o1:high",
  },
  {
    routerSlug: "openai/gpt-5-nano",
    urlSlug: "openai--gpt-5-nano",
    name: "GPT 5 Nano",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-nano",
  },
  {
    routerSlug: "openai/gpt-4o-2024-05-13",
    urlSlug: "openai--gpt-4o-2024-05-13",
    name: "GPT 4o 2024 05 13",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4o-2024-05-13",
  },
  {
    routerSlug: "openai/gpt-5",
    urlSlug: "openai--gpt-5",
    name: "GPT 5",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5",
  },
  {
    routerSlug: "openai/o3-mini:high",
    urlSlug: "openai--o3-mini__high",
    name: "O3 Mini:high",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3-mini:high",
  },
  {
    routerSlug: "openai/o4-mini:medium",
    urlSlug: "openai--o4-mini__medium",
    name: "O4 Mini:medium",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini:medium",
  },
  {
    routerSlug: "openai/gpt-5-nano:flex",
    urlSlug: "openai--gpt-5-nano__flex",
    name: "GPT 5 Nano:flex",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-nano:flex",
  },
  {
    routerSlug: "openai/o1-pro",
    urlSlug: "openai--o1-pro",
    name: "O1 Pro",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o1-pro",
  },
  {
    routerSlug: "openai/gpt-5-mini:priority",
    urlSlug: "openai--gpt-5-mini__priority",
    name: "GPT 5 Mini:priority",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-mini:priority",
  },
  {
    routerSlug: "openai/o4-mini-deep-research",
    urlSlug: "openai--o4-mini-deep-research",
    name: "O4 Mini Deep Research",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o4-mini-deep-research",
  },
  {
    routerSlug: "openai/o1:low",
    urlSlug: "openai--o1__low",
    name: "O1:low",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o1:low",
  },
  {
    routerSlug: "openai/gpt-5.1-chat",
    urlSlug: "openai--gpt-5.1-chat",
    name: "GPT 5.1 Chat",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5.1-chat",
  },
  {
    routerSlug: "openai/gpt-5.2-chat",
    urlSlug: "openai--gpt-5.2-chat",
    name: "GPT 5.2 Chat",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5.2-chat",
  },
  {
    routerSlug: "openai/gpt-4o",
    urlSlug: "openai--gpt-4o",
    name: "GPT 4o",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4o",
  },
  {
    routerSlug: "openai/o3-mini:medium",
    urlSlug: "openai--o3-mini__medium",
    name: "O3 Mini:medium",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o3-mini:medium",
  },
  {
    routerSlug: "openai/gpt-5.2",
    urlSlug: "openai--gpt-5.2",
    name: "GPT 5.2",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5.2",
  },
  {
    routerSlug: "openai/gpt-5-chat",
    urlSlug: "openai--gpt-5-chat",
    name: "GPT 5 Chat",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-chat",
  },
  {
    routerSlug: "openai/gpt-4.1-nano",
    urlSlug: "openai--gpt-4.1-nano",
    name: "GPT 4.1 Nano",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-4.1-nano",
  },
  {
    routerSlug: "openai/gpt-5-mini",
    urlSlug: "openai--gpt-5-mini",
    name: "GPT 5 Mini",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5-mini",
  },
  {
    routerSlug: "openai/o1",
    urlSlug: "openai--o1",
    name: "O1",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "o1",
  },
  {
    routerSlug: "openai/gpt-5.1",
    urlSlug: "openai--gpt-5.1",
    name: "GPT 5.1",
    providerSlug: "openai",
    providerName: "OpenAI",
    familySlug: null,
    modelName: "gpt-5.1",
  },
  {
    routerSlug: "groq/llama-4-scout",
    urlSlug: "groq--llama-4-scout",
    name: "Llama 4 Scout",
    providerSlug: "groq",
    providerName: "Groq",
    familySlug: null,
    modelName: "llama-4-scout",
  },
  {
    routerSlug: "groq/openai/gpt-oss-20b",
    urlSlug: "groq--openai--gpt-oss-20b",
    name: "GPT OSS 20b",
    providerSlug: "groq",
    providerName: "Groq",
    familySlug: "openai",
    modelName: "gpt-oss-20b",
  },
  {
    routerSlug: "groq/openai/gpt-oss-120b",
    urlSlug: "groq--openai--gpt-oss-120b",
    name: "GPT OSS 120b",
    providerSlug: "groq",
    providerName: "Groq",
    familySlug: "openai",
    modelName: "gpt-oss-120b",
  },
  {
    routerSlug: "groq/moonshotai/Kimi-K2-Instruct-0905",
    urlSlug: "groq--moonshotai--Kimi-K2-Instruct-0905",
    name: "Kimi K2 Instruct 0905",
    providerSlug: "groq",
    providerName: "Groq",
    familySlug: "moonshotai",
    modelName: "Kimi-K2-Instruct-0905",
  },
  {
    routerSlug: "groq/moonshotai/kimi-k2-instruct",
    urlSlug: "groq--moonshotai--kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    providerSlug: "groq",
    providerName: "Groq",
    familySlug: "moonshotai",
    modelName: "kimi-k2-instruct",
  },
  {
    routerSlug: "smart/task",
    urlSlug: "smart--task",
    name: "Task",
    providerSlug: "smart",
    providerName: "eachlabs Smart",
    familySlug: null,
    modelName: "task",
  },
  {
    routerSlug: "perplexity/sonar-pro",
    urlSlug: "perplexity--sonar-pro",
    name: "Sonar Pro",
    providerSlug: "perplexity",
    providerName: "Perplexity",
    familySlug: null,
    modelName: "sonar-pro",
  },
  {
    routerSlug: "perplexity/sonar-reasoning-pro",
    urlSlug: "perplexity--sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    providerSlug: "perplexity",
    providerName: "Perplexity",
    familySlug: null,
    modelName: "sonar-reasoning-pro",
  },
  {
    routerSlug: "perplexity/sonar",
    urlSlug: "perplexity--sonar",
    name: "Sonar",
    providerSlug: "perplexity",
    providerName: "Perplexity",
    familySlug: null,
    modelName: "sonar",
  },
  {
    routerSlug: "moonshot/kimi-k2-0711-preview",
    urlSlug: "moonshot--kimi-k2-0711-preview",
    name: "Kimi K2 0711 Preview",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2-0711-preview",
  },
  {
    routerSlug: "moonshot/kimi-k2-0905-preview",
    urlSlug: "moonshot--kimi-k2-0905-preview",
    name: "Kimi K2 0905 Preview",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2-0905-preview",
  },
  {
    routerSlug: "moonshot/kimi-k2-thinking",
    urlSlug: "moonshot--kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2-thinking",
  },
  {
    routerSlug: "moonshot/kimi-k2-turbo-preview",
    urlSlug: "moonshot--kimi-k2-turbo-preview",
    name: "Kimi K2 Turbo Preview",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2-turbo-preview",
  },
  {
    routerSlug: "moonshot/kimi-k2.5",
    urlSlug: "moonshot--kimi-k2.5",
    name: "Kimi K2.5",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2.5",
  },
  {
    routerSlug: "moonshot/kimi-k2-thinking-turbo",
    urlSlug: "moonshot--kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo",
    providerSlug: "moonshot",
    providerName: "Moonshot AI",
    familySlug: null,
    modelName: "kimi-k2-thinking-turbo",
  },
  {
    routerSlug: "vertex/claude-sonnet-4",
    urlSlug: "vertex--claude-sonnet-4",
    name: "Claude Sonnet 4",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-sonnet-4",
  },
  {
    routerSlug: "vertex/gemini-3-pro-image-preview",
    urlSlug: "vertex--gemini-3-pro-image-preview",
    name: "Gemini 3 Pro Image Preview",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-3-pro-image-preview",
  },
  {
    routerSlug: "vertex/claude-sonnet-4-5",
    urlSlug: "vertex--claude-sonnet-4-5",
    name: "Claude Sonnet 4 5",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-sonnet-4-5",
  },
  {
    routerSlug: "vertex/gemini-2.5-flash",
    urlSlug: "vertex--gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-2.5-flash",
  },
  {
    routerSlug: "vertex/claude-3-5-sonnet",
    urlSlug: "vertex--claude-3-5-sonnet",
    name: "Claude 3 5 Sonnet",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-3-5-sonnet",
  },
  {
    routerSlug: "vertex/gemini-2.5-flash-lite",
    urlSlug: "vertex--gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-2.5-flash-lite",
  },
  {
    routerSlug: "vertex/claude-haiku-4-5",
    urlSlug: "vertex--claude-haiku-4-5",
    name: "Claude Haiku 4 5",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-haiku-4-5",
  },
  {
    routerSlug: "vertex/claude-opus-4",
    urlSlug: "vertex--claude-opus-4",
    name: "Claude Opus 4",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-opus-4",
  },
  {
    routerSlug: "vertex/claude-opus-4-6",
    urlSlug: "vertex--claude-opus-4-6",
    name: "Claude Opus 4 6",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-opus-4-6",
  },
  {
    routerSlug: "vertex/claude-opus-4-1",
    urlSlug: "vertex--claude-opus-4-1",
    name: "Claude Opus 4 1",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-opus-4-1",
  },
  {
    routerSlug: "vertex/claude-opus-4-5",
    urlSlug: "vertex--claude-opus-4-5",
    name: "Claude Opus 4 5",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-opus-4-5",
  },
  {
    routerSlug: "vertex/gemini-3-pro-preview",
    urlSlug: "vertex--gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-3-pro-preview",
  },
  {
    routerSlug: "vertex/gemini-3-flash-preview",
    urlSlug: "vertex--gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-3-flash-preview",
  },
  {
    routerSlug: "vertex/claude-3-7-sonnet",
    urlSlug: "vertex--claude-3-7-sonnet",
    name: "Claude 3 7 Sonnet",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "claude-3-7-sonnet",
  },
  {
    routerSlug: "vertex/gemini-2.5-pro",
    urlSlug: "vertex--gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-2.5-pro",
  },
  {
    routerSlug: "vertex/gemini-2.5-flash-image-preview",
    urlSlug: "vertex--gemini-2.5-flash-image-preview",
    name: "Gemini 2.5 Flash Image Preview",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-2.5-flash-image-preview",
  },
  {
    routerSlug: "vertex/gemini-3.1-flash-lite-preview",
    urlSlug: "vertex--gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    providerSlug: "vertex",
    providerName: "Google Vertex",
    familySlug: null,
    modelName: "gemini-3.1-flash-lite-preview",
  },
  {
    routerSlug: "minimaxi/MiniMax-M2",
    urlSlug: "minimaxi--MiniMax-M2",
    name: "MiniMax M2",
    providerSlug: "minimaxi",
    providerName: "MiniMax",
    familySlug: null,
    modelName: "MiniMax-M2",
  },
  {
    routerSlug: "minimaxi/MiniMax-M2.5",
    urlSlug: "minimaxi--MiniMax-M2.5",
    name: "MiniMax M2.5",
    providerSlug: "minimaxi",
    providerName: "MiniMax",
    familySlug: null,
    modelName: "MiniMax-M2.5",
  },
  {
    routerSlug: "alibaba/qwen3-coder-flash",
    urlSlug: "alibaba--qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen3-coder-flash",
  },
  {
    routerSlug: "alibaba/qwen-plus",
    urlSlug: "alibaba--qwen-plus",
    name: "Qwen Plus",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen-plus",
  },
  {
    routerSlug: "alibaba/qwen3-coder-plus",
    urlSlug: "alibaba--qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen3-coder-plus",
  },
  {
    routerSlug: "alibaba/qwen3-max",
    urlSlug: "alibaba--qwen3-max",
    name: "Qwen3 Max",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen3-max",
  },
  {
    routerSlug: "alibaba/qwen-turbo",
    urlSlug: "alibaba--qwen-turbo",
    name: "Qwen Turbo",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen-turbo",
  },
  {
    routerSlug: "alibaba/qwen-max",
    urlSlug: "alibaba--qwen-max",
    name: "Qwen Max",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen-max",
  },
  {
    routerSlug: "alibaba/qwen3-30b-a3b-instruct-2507",
    urlSlug: "alibaba--qwen3-30b-a3b-instruct-2507",
    name: "Qwen3 30b A3b Instruct 2507",
    providerSlug: "alibaba",
    providerName: "Alibaba Qwen",
    familySlug: null,
    modelName: "qwen3-30b-a3b-instruct-2507",
  },
  {
    routerSlug: "deepinfra/meta-llama/Llama-3.3-70B-Instruct",
    urlSlug: "deepinfra--meta-llama--Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Llama-3.3-70B-Instruct",
  },
  {
    routerSlug: "deepinfra/zai-org/GLM-4.5-Air",
    urlSlug: "deepinfra--zai-org--GLM-4.5-Air",
    name: "GLM 4.5 Air",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "zai-org",
    modelName: "GLM-4.5-Air",
  },
  {
    routerSlug: "deepinfra/Qwen/Qwen3-Coder-480B-A35B-Instruct",
    urlSlug: "deepinfra--Qwen--Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "Qwen",
    modelName: "Qwen3-Coder-480B-A35B-Instruct",
  },
  {
    routerSlug: "deepinfra/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    urlSlug: "deepinfra--deepseek-ai--DeepSeek-R1-Distill-Llama-70B",
    name: "DeepSeek R1 Distill Llama 70B",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-R1-Distill-Llama-70B",
  },
  {
    routerSlug: "deepinfra/Qwen/Qwen2.5-72B-Instruct",
    urlSlug: "deepinfra--Qwen--Qwen2.5-72B-Instruct",
    name: "Qwen2.5 72B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "Qwen",
    modelName: "Qwen2.5-72B-Instruct",
  },
  {
    routerSlug: "deepinfra/deepseek-ai/DeepSeek-V3.1",
    urlSlug: "deepinfra--deepseek-ai--DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-V3.1",
  },
  {
    routerSlug: "deepinfra/Qwen/Qwen2.5-Coder-32B-Instruct",
    urlSlug: "deepinfra--Qwen--Qwen2.5-Coder-32B-Instruct",
    name: "Qwen2.5 Coder 32B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "Qwen",
    modelName: "Qwen2.5-Coder-32B-Instruct",
  },
  {
    routerSlug: "deepinfra/deepseek-ai/DeepSeek-R1",
    urlSlug: "deepinfra--deepseek-ai--DeepSeek-R1",
    name: "DeepSeek R1",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-R1",
  },
  {
    routerSlug: "deepinfra/Qwen/Qwen3-235B-A22B",
    urlSlug: "deepinfra--Qwen--Qwen3-235B-A22B",
    name: "Qwen3 235B A22B",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "Qwen",
    modelName: "Qwen3-235B-A22B",
  },
  {
    routerSlug: "deepinfra/deepseek-ai/DeepSeek-V3",
    urlSlug: "deepinfra--deepseek-ai--DeepSeek-V3",
    name: "DeepSeek V3",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "deepseek-ai",
    modelName: "DeepSeek-V3",
  },
  {
    routerSlug: "deepinfra/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    urlSlug: "deepinfra--meta-llama--Meta-Llama-3.1-8B-Instruct-Turbo",
    name: "Meta Llama 3.1 8B Instruct Turbo",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3.1-8B-Instruct-Turbo",
  },
  {
    routerSlug: "deepinfra/microsoft/phi-4",
    urlSlug: "deepinfra--microsoft--phi-4",
    name: "Phi 4",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "microsoft",
    modelName: "phi-4",
  },
  {
    routerSlug: "deepinfra/meta-llama/Meta-Llama-3.1-70B-Instruct",
    urlSlug: "deepinfra--meta-llama--Meta-Llama-3.1-70B-Instruct",
    name: "Meta Llama 3.1 70B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3.1-70B-Instruct",
  },
  {
    routerSlug: "deepinfra/meta-llama/Llama-3.3-70B-Instruct-Turbo",
    urlSlug: "deepinfra--meta-llama--Llama-3.3-70B-Instruct-Turbo",
    name: "Llama 3.3 70B Instruct Turbo",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Llama-3.3-70B-Instruct-Turbo",
  },
  {
    routerSlug: "deepinfra/Qwen/Qwen3-32B",
    urlSlug: "deepinfra--Qwen--Qwen3-32B",
    name: "Qwen3 32B",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "Qwen",
    modelName: "Qwen3-32B",
  },
  {
    routerSlug: "deepinfra/zai-org/GLM-4.5",
    urlSlug: "deepinfra--zai-org--GLM-4.5",
    name: "GLM 4.5",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "zai-org",
    modelName: "GLM-4.5",
  },
  {
    routerSlug: "deepinfra/meta-llama/Meta-Llama-3.1-405B-Instruct",
    urlSlug: "deepinfra--meta-llama--Meta-Llama-3.1-405B-Instruct",
    name: "Meta Llama 3.1 405B Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Meta-Llama-3.1-405B-Instruct",
  },
  {
    routerSlug: "deepinfra/meta-llama/Llama-3.2-90B-Vision-Instruct",
    urlSlug: "deepinfra--meta-llama--Llama-3.2-90B-Vision-Instruct",
    name: "Llama 3.2 90B Vision Instruct",
    providerSlug: "deepinfra",
    providerName: "DeepInfra",
    familySlug: "meta-llama",
    modelName: "Llama-3.2-90B-Vision-Instruct",
  },
  {
    routerSlug: "byteplus/seed-2-0-mini",
    urlSlug: "byteplus--seed-2-0-mini",
    name: "Seed 2 0 Mini",
    providerSlug: "byteplus",
    providerName: "BytePlus",
    familySlug: null,
    modelName: "seed-2-0-mini",
  },
];
